name: Push Docker Hub Public Images to ACR

# Add below the image that you wish to add to the ACR
strategy:
  matrix:
    postgres:
      imageName: 'postgres'
      version: '11.9'
    postgres:
      imageName: 'postgres'
      version: '11.3'
    keycloak:
      imageName: 'jboss/keycloak'
      version: '11.0.3'
    logstash:
      imageName: 'logstash'
      version: '6.8.13'

trigger:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

variables:
  acrName: hmctspublic 
  targetRegistry: hmctspublic.azurecr.io
  serviceConnection: 'azurerm-prod'

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: DockerInstaller@0
  displayName: 'Install DockerCLI'
  inputs:
    dockerVersion: '19.03.13'

- task: AzureCLI@2
  displayName: "Login to ACR"
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr login --name $(acrName)'

- task: Bash@3
  displayName: "Pull the official image"
  inputs:
    targetType: 'inline'
    script: 'docker pull $(imageName):$(version)'

- task: Bash@3
  displayName: "Create an alias of the image"
  inputs:
    targetType: 'inline'
    script: 'docker tag $(imageName):$(version) $(targetRegistry)/imported/$(imageName):$(version)'

- task: Bash@3
  displayName: "Push the image to ACR"
  inputs:
    targetType: 'inline'
    script: 'docker push $(targetRegistry)/imported/$(imageName):$(version)'
