name: Copy Docker Public Images
trigger:
- master

variables:
  acrName: hmctssandbox 
  targetRegistry: hmctssandbox.azurecr.io
  serviceConnection: 'azurerm-sandbox'
  dockerImage: 'postgres:11.9'

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: DockerInstaller@0
  displayName: 'Install DockerCLI'
  inputs:
    dockerVersion: '19.03.13'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr login --name $(acrName)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker pull image $(dockerImage)'